#!/bin/env ruby


require 'pty'
require 'io/console'

IO.popen "zsh -n > /dev/null 2>&1", "w" do |f|
    f.puts ARGV[0]
end

if $?.exitstatus != 0
    exit 1
end

t =  nil
lncnt = ARGV[0].count("\n")

if lncnt == 0
    ARGV[0] += "\n"
    lncnt = 1
end

PTY.spawn('zsh -in') do |r,w,pid|
    w.echo = false
    r.echo = false
    line = ''
    t = Thread.new do
        loop do
            line += r.readpartial(1024) rescue break
            #p line
            #p line.scan(/\r\r\n/).length
            if line.scan(/\r\r\n/).length >= lncnt && $' && !$'.empty?
                #p "kill #{pid}"
                Process.kill('KILL', pid)
                if line =~ /\r \r\r% \z/
                    #p "acceptable"
                    exit 0
                else
                    #p "unacceptable"
                    exit 1
                end
            end
        end
    end
    w.write ARGV[0]
    Thread.pass
end
t.join
